#ifndef __GROUPMETAMINIMAP_H_AST_H_
#define __GROUPMETAMINIMAP_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \groupMetaMinimap.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MapServer\..\Common\group\groupMetaMinimap.h"
#endif



//auto-generated staticdefine for enum ArchitectMapType
//autogeneratednocheckin
extern StaticDefineInt ArchitectMapTypeEnum[];



//auto-generated staticdefine for enum ArchitectMapColors
//autogeneratednocheckin
extern StaticDefineInt ArchitectMapColorsEnum[];


extern ParseTable parse_ArchitectMapComponentPlace[];

extern ParseTable parse_ArchitectMapComponent[];

extern ParseTable parse_ArchitectMapSubMap[];

extern ParseTable parse_ArchitectMapHeader[];


#endif

