//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_mapserver(void);
extern void _mapserver_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_ArchitectMapComponent(void);
extern void autoStruct_fixup_ArchitectMapComponentPlace(void);
extern void autoStruct_fixup_ArchitectMapHeader(void);
extern void autoStruct_fixup_ArchitectMapSubMap(void);
extern void autoStruct_fixup_MMElement(void);
extern void autoStruct_fixup_MMElementList(void);
extern void autoStruct_fixup_MMRegion(void);
extern void autoStruct_fixup_MMRegionButton(void);
extern void autoStruct_fixup_MMScrollSet_Loader(void);
extern void autoStruct_fixup_MapLimit(void);
extern void autoStruct_fixup_MissionHeaderDescription(void);
extern void autoStruct_fixup_MissionSearchGuestBio(void);
extern void autoStruct_fixup_MissionSearchHeader(void);
extern void autoStruct_fixup_MissionSearchParams(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);
void doAutoRuns_AILib_0(void);
void doAutoRuns_AILib_1(void);
void doAutoRuns_AILib_2(void);
void doAutoRuns_AILib_3(void);
void doAutoRuns_AILib_4(void);


void doAutoRuns_mapserver_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_0();
	doAutoRuns_AILib_0();
	_mapserver_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_mapserver_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_1();
	doAutoRuns_AILib_1();
	Add_Auto_Cmds_mapserver();
	autoStruct_fixup_ArchitectMapComponent();
	autoStruct_fixup_ArchitectMapComponentPlace();
	autoStruct_fixup_ArchitectMapHeader();
	autoStruct_fixup_ArchitectMapSubMap();
	autoStruct_fixup_MMElement();
	autoStruct_fixup_MMElementList();
	autoStruct_fixup_MMRegion();
	autoStruct_fixup_MMRegionButton();
	autoStruct_fixup_MMScrollSet_Loader();
	autoStruct_fixup_MapLimit();
	autoStruct_fixup_MissionHeaderDescription();
	autoStruct_fixup_MissionSearchGuestBio();
	autoStruct_fixup_MissionSearchHeader();
	autoStruct_fixup_MissionSearchParams();
}



void doAutoRuns_mapserver_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_2();
	doAutoRuns_AILib_2();
}



void doAutoRuns_mapserver_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_3();
	doAutoRuns_AILib_3();
}



void doAutoRuns_mapserver_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_4();
	doAutoRuns_AILib_4();
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_mapserver(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_mapserver_0();
	doAutoRuns_mapserver_1();
	doAutoRuns_mapserver_2();
	doAutoRuns_mapserver_3();
	doAutoRuns_mapserver_4();
	return 0;
}

void do_auto_runs(void)
{
	MagicAutoRunFunc_mapserver();
}

};


#if 0
PARSABLE
16
"Add_Auto_Cmds_mapserver" "autogen_magiccommands" 1 "" "" 
"_mapserver_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_ArchitectMapComponent" "c:\game\code\CoH\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapComponentPlace" "c:\game\code\CoH\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapHeader" "c:\game\code\CoH\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapSubMap" "c:\game\code\CoH\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_MMElement" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMElementList" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegion" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegionButton" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMScrollSet_Loader" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MapLimit" "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MissionHeaderDescription" "c:\game\code\CoH\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchGuestBio" "c:\game\code\CoH\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchHeader" "c:\game\code\CoH\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchParams" "c:\game\code\CoH\MapServer\..\Common\MissionSearch.h" 1 "" "" 
#endif
