#ifndef __PLAYERCREATEDSTORYARCVALIDATE_H_AST_H_
#define __PLAYERCREATEDSTORYARCVALIDATE_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \playerCreatedStoryarcValidate.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h"
#endif



//auto-generated staticdefine for enum SpecialAction
//autogeneratednocheckin
extern StaticDefineInt SpecialActionEnum[];



//auto-generated staticdefine for enum PlayerCreatedDetailType
//autogeneratednocheckin
extern StaticDefineInt PlayerCreatedDetailTypeEnum[];


extern ParseTable parse_MapLimit[];

extern ParseTable parse_MMElement[];

extern ParseTable parse_MMElementList[];

extern ParseTable parse_MMRegionButton[];

extern ParseTable parse_MMRegion[];

extern ParseTable parse_MMScrollSet_Loader[];


#endif

