#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MapServer\.\script\zoneevents\ScriptedZoneEvent.c"
#endif



//auto-generated staticdefine for enum glowieControlType
//autogeneratednocheckin
StaticDefineInt glowieControlTypeEnum[] =
{
	DEFINE_INT
	{ "Place", glowieControl_Place},
	{ "Remove", glowieControl_Remove},
	{ "Activate", glowieControl_Activate},
	{ "Deactivate", glowieControl_Deactivate},
	{ "Mark", glowieControl_Mark},
	{ "ClearMemory", glowieControl_ClearMemory},
	DEFINE_END
};



//auto-generated staticdefine for enum teamRespawnFlags
//autogeneratednocheckin
StaticDefineInt teamRespawnFlagsEnum[] =
{
	DEFINE_INT
	{ "UsePlayerCount", teamRespawnFlags_UsePlayerCount},
	{ "PlaceHolder", teamRespawnFlags_PlaceHolder},
	DEFINE_END
};



//auto-generated staticdefine for enum teamControlType
//autogeneratednocheckin
StaticDefineInt teamControlTypeEnum[] =
{
	DEFINE_INT
	{ "Activate", teamControl_Activate},
	{ "Deactivate", teamControl_Deactivate},
	{ "DoBehavior", teamControl_DoBehavior},
	{ "Detach", teamControl_Detach},
	{ "ForceSpawn", teamControl_ForceSpawn},
	{ "SetHealth", teamControl_SetHealth},
	DEFINE_END
};



//auto-generated staticdefine for enum doorControlType
//autogeneratednocheckin
StaticDefineInt doorControlTypeEnum[] =
{
	DEFINE_INT
	{ "Unlock", doorControl_Unlock},
	{ "Lock", doorControl_Lock},
	DEFINE_END
};



//auto-generated staticdefine for enum portControlType
//autogeneratednocheckin
StaticDefineInt portControlTypeEnum[] =
{
	DEFINE_INT
	{ "Activate", portControl_Activate},
	{ "Deactivate", portControl_Deactivate},
	DEFINE_END
};



//auto-generated staticdefine for enum gurneyControlType
//autogeneratednocheckin
StaticDefineInt gurneyControlTypeEnum[] =
{
	DEFINE_INT
	{ "EnableRezWindow", gurneyControl_EnableRezWindow},
	{ "DisableRezWindow", gurneyControl_DisableRezWindow},
	{ "Activate", gurneyControl_Activate},
	{ "Deactivate", gurneyControl_Deactivate},
	DEFINE_END
};



//auto-generated staticdefine for enum timerControlType
//autogeneratednocheckin
StaticDefineInt timerControlTypeEnum[] =
{
	DEFINE_INT
	{ "Add", timerControl_Add},
	{ "Subtract", timerControl_Subtract},
	{ "Reset", timerControl_Reset},
	{ "Delete", timerControl_Delete},
	DEFINE_END
};



//auto-generated staticdefine for enum triggerDeckType
//autogeneratednocheckin
StaticDefineInt triggerDeckTypeEnum[] =
{
	DEFINE_INT
	{ "NeverShuffle", triggerDeck_NeverShuffle},
	{ "ShuffleAlways", triggerDeck_ShuffleAlways},
	{ "ShuffleAtCount", triggerDeck_ShuffleAtCount},
	{ "ShuffleAtEnd", triggerDeck_ShuffleAtEnd},
	DEFINE_END
};



//auto-generated staticdefine for enum counterType
//autogeneratednocheckin
StaticDefineInt counterTypeEnum[] =
{
	DEFINE_INT
	{ "VillainGroup", counter_VillainGroup},
	{ "Team", counter_Team},
	{ "Name", counter_Name},
	{ "Click", counter_Click},
	{ "ZEPlayers", counter_ZEPlayers},
	{ "ZEPlayersAlive", counter_ZEPlayersAlive},
	{ "ZEPlayersPhased", counter_ZEPlayersPhased},
	{ "ZEPlayersActive", counter_ZEPlayersActive},
	{ "BossHealth", counter_BossHealth},
	{ "PlayerDeaths", counter_PlayerDeaths},
	DEFINE_END
};



//auto-generated staticdefine for enum counterDirection
//autogeneratednocheckin
StaticDefineInt counterDirectionEnum[] =
{
	DEFINE_INT
	{ "Up", counter_Up},
	{ "Down", counter_Down},
	DEFINE_END
};



//auto-generated staticdefine for enum objectiveType
//autogeneratednocheckin
StaticDefineInt objectiveTypeEnum[] =
{
	DEFINE_INT
	{ "VillainGroup", objective_VillainGroup},
	{ "Team", objective_Team},
	{ "Named", objective_Named},
	{ "Glowie", objective_Glowie},
	{ "Defendable", objective_Defendable},
	DEFINE_END
};



//auto-generated staticdefine for enum itemType
//autogeneratednocheckin
StaticDefineInt itemTypeEnum[] =
{
	DEFINE_INT
	{ "BarBlue", itemType_BarBlue},
	{ "BarGold", itemType_BarGold},
	{ "BarRed", itemType_BarRed},
	{ "Text", itemType_Text},
	{ "CenterText", itemType_CenterText},
	{ "Timer", itemType_Timer},
	DEFINE_END
};

