#ifndef __SCRIPTEDZONEEVENT_C_AST_H_
#define __SCRIPTEDZONEEVENT_C_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \ScriptedZoneEvent.c
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MapServer\.\script\zoneevents\ScriptedZoneEvent.c"
#endif



//auto-generated staticdefine for enum glowieControlType
//autogeneratednocheckin
extern StaticDefineInt glowieControlTypeEnum[];



//auto-generated staticdefine for enum teamRespawnFlags
//autogeneratednocheckin
extern StaticDefineInt teamRespawnFlagsEnum[];



//auto-generated staticdefine for enum teamControlType
//autogeneratednocheckin
extern StaticDefineInt teamControlTypeEnum[];



//auto-generated staticdefine for enum doorControlType
//autogeneratednocheckin
extern StaticDefineInt doorControlTypeEnum[];



//auto-generated staticdefine for enum portControlType
//autogeneratednocheckin
extern StaticDefineInt portControlTypeEnum[];



//auto-generated staticdefine for enum gurneyControlType
//autogeneratednocheckin
extern StaticDefineInt gurneyControlTypeEnum[];



//auto-generated staticdefine for enum timerControlType
//autogeneratednocheckin
extern StaticDefineInt timerControlTypeEnum[];



//auto-generated staticdefine for enum triggerDeckType
//autogeneratednocheckin
extern StaticDefineInt triggerDeckTypeEnum[];



//auto-generated staticdefine for enum counterType
//autogeneratednocheckin
extern StaticDefineInt counterTypeEnum[];



//auto-generated staticdefine for enum counterDirection
//autogeneratednocheckin
extern StaticDefineInt counterDirectionEnum[];



//auto-generated staticdefine for enum objectiveType
//autogeneratednocheckin
extern StaticDefineInt objectiveTypeEnum[];



//auto-generated staticdefine for enum itemType
//autogeneratednocheckin
extern StaticDefineInt itemTypeEnum[];



#endif

