#ifndef __MISSIONSERVERSEARCH_H_AST_H_
#define __MISSIONSERVERSEARCH_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MissionServerSearch.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h"
#endif


extern ParseTable parse_MissionServerSearch[];

extern ParseTable parse_MissionServerQuotedSearch[];

extern ParseTable parse_MissionServerCSearch[];

extern ParseTable parse_MissionServerSubstringSearch[];


#endif

