#ifndef __MISSIONSERVER_H_AST_H_
#define __MISSIONSERVER_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MissionServer.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\.\MissionServer.h"
#endif



//auto-generated staticdefine for enum MissionComplaintType
//autogeneratednocheckin
extern StaticDefineInt MissionComplaintTypeEnum[];


extern ParseTable parse_MissionComplaint[];

extern ParseTable parse_MissionAuth[];

extern ParseTable parse_MissionServerArc[];

extern ParseTable parse_MissionServerShard[];

extern ParseTable parse_MissionServerCfg[];

extern ParseTable parse_MissionServerVars[];


#endif

