#ifndef __MISSIONSEARCH_H_AST_H_
#define __MISSIONSEARCH_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MissionSearch.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\..\Common\MissionSearch.h"
#endif



//auto-generated staticdefine for enum AuthRegion
//autogeneratednocheckin
extern StaticDefineInt AuthRegionEnum[];



//auto-generated staticdefine for enum MissionRating
//autogeneratednocheckin
extern StaticDefineInt MissionRatingEnum[];



//auto-generated staticdefine for enum MissionHonors
//autogeneratednocheckin
extern StaticDefineInt MissionHonorsEnum[];



//auto-generated staticdefine for enum MissionBan
//autogeneratednocheckin
extern StaticDefineInt MissionBanEnum[];


extern ParseTable parse_MissionSearchParams[];

extern ParseTable parse_MissionHeaderDescription[];

extern ParseTable parse_MissionSearchHeader[];

extern ParseTable parse_MissionSearchGuestBio[];


#endif

