#ifndef __MISSIONSERVERJOURNAL_C_AST_H_
#define __MISSIONSERVERJOURNAL_C_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MissionServerJournal.c
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\.\MissionServerJournal.c"
#endif



//auto-generated staticdefine for enum ArcJournalType
//autogeneratednocheckin
extern StaticDefineInt ArcJournalTypeEnum[];



//auto-generated staticdefine for enum UserJournalType
//autogeneratednocheckin
extern StaticDefineInt UserJournalTypeEnum[];


extern ParseTable parse_ArcJournal[];

extern ParseTable parse_UserJournal[];


#endif

