#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h"
#endif

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MissionServerSearch
ParseTable parse_MissionServerSearch[] =
{
	{ "MissionServerSearch", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionServerSearch), 0, NULL, 0 },
	{ "str",					TOK_STRUCTPARAM | TOK_PRIMARY_KEY | TOK_STRING(MissionServerSearch, str, 0), NULL },
	{ "arcids",					TOK_INTARRAY(MissionServerSearch, arcids),  NULL},
	{ "hits",					TOK_AUTOINT(MissionServerSearch, hits, 0), NULL },
	{ "nextid",					TOK_AUTOINT(MissionServerSearch, nextid, 0), NULL },
	{ "timestamp",				TOK_AUTOINT(MissionServerSearch, timestamp, 0), NULL },
	{ "End",					TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionServerSearch()
{
	int iSize = sizeof(MissionServerSearch);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionServerSearch, iSize, "MissionServerSearch", NULL, "MissionServerSearch.h");
	return 0;
};

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MissionServerQuotedSearch
ParseTable parse_MissionServerQuotedSearch[] =
{
	{ "MissionServerQuotedSearch", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionServerQuotedSearch), 0, NULL, 0 },
	{ "str",						TOK_STRUCTPARAM | TOK_PRIMARY_KEY | TOK_STRING(MissionServerQuotedSearch, str, 0), NULL },
	{ "arcids",						TOK_INTARRAY(MissionServerQuotedSearch, arcids),  NULL},
	{ "hits",						TOK_AUTOINT(MissionServerQuotedSearch, hits, 0), NULL },
	{ "nextid",						TOK_AUTOINT(MissionServerQuotedSearch, nextid, 0), NULL },
	{ "End",						TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionServerQuotedSearch()
{
	int iSize = sizeof(MissionServerQuotedSearch);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionServerQuotedSearch, iSize, "MissionServerQuotedSearch", NULL, "MissionServerSearch.h");
	return 0;
};

//autogeneratednocheckin
extern ParseTable parse_MissionSearchParams[];
//Structparser.exe autogenerated ParseTable for struct MissionServerCSearch
ParseTable parse_MissionServerCSearch[] =
{
	{ "MissionServerCSearch", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionServerCSearch), 0, NULL, 0 },
	{ "str",					TOK_STRUCTPARAM | TOK_PRIMARY_KEY | TOK_STRING(MissionServerCSearch, str, 0), NULL },
	{ "arcids",					TOK_INTARRAY(MissionServerCSearch, arcids),  NULL},
	{ "hits",					TOK_AUTOINT(MissionServerCSearch, hits, 0), NULL },
	{ "nextid",					TOK_AUTOINT(MissionServerCSearch, nextid, 0), NULL },
	{ "params",					TOK_EMBEDDEDSTRUCT(MissionServerCSearch, params, parse_MissionSearchParams)},
	{ "End",					TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionServerCSearch()
{
	int iSize = sizeof(MissionServerCSearch);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionServerCSearch, iSize, "MissionServerCSearch", NULL, "MissionServerSearch.h");
	return 0;
};

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MissionServerSubstringSearch
ParseTable parse_MissionServerSubstringSearch[] =
{
	{ "MissionServerSubstringSearch", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionServerSubstringSearch), 0, NULL, 0 },
	{ "substring",						TOK_STRUCTPARAM | TOK_PRIMARY_KEY | TOK_STRING(MissionServerSubstringSearch, substring, 0), NULL },
	{ "hits",							TOK_AUTOINT(MissionServerSubstringSearch, hits, 0), NULL },
	{ "End",							TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionServerSubstringSearch()
{
	int iSize = sizeof(MissionServerSubstringSearch);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionServerSubstringSearch, iSize, "MissionServerSubstringSearch", NULL, "MissionServerSearch.h");
	return 0;
};

