//This file contains data and prototypes for magic commands. It is autogenerated by StructParser


//autogeneratednocheckin

#include "cmdparse.h"
#include "textparser.h"

static char sMissionServerName[] = "MissionServer";




extern CmdList gRemoteCmdList;
extern CmdList gSlowRemoteCmdList;


void Add_Auto_Cmds_MissionServer(void)
{
};




#if 0
PARSABLE
0
0
#endif
