#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\MissionServer\.\MissionServerJournal.c"
#endif



//auto-generated staticdefine for enum ArcJournalType
//autogeneratednocheckin
StaticDefineInt ArcJournalTypeEnum[] =
{
	DEFINE_INT
	{ "UNPUBLISH", ARCJOURNAL_UNPUBLISH},
	{ "INVALIDATE", ARCJOURNAL_INVALIDATE},
	{ "HONORS", ARCJOURNAL_HONORS},
	{ "BANPULLED", ARCJOURNAL_BANPULLED},
	{ "VOTESRATING", ARCJOURNAL_VOTESRATING},
	{ "TOTALCOMPLETIONS", ARCJOURNAL_TOTALCOMPLETIONS},
	{ "KEYWORDS", ARCJOURNAL_KEYWORDS},
	{ "PLAYABLEINVALIDATE", ARCJOURNAL_PLAYABLEINVALIDATE},
	{ "TOTALSTARTS", ARCJOURNAL_TOTALSTARTS},
	{ "TYPES", ARCJOURNAL_TYPES},
	DEFINE_END
};



//auto-generated staticdefine for enum UserJournalType
//autogeneratednocheckin
StaticDefineInt UserJournalTypeEnum[] =
{
	DEFINE_INT
	{ "COMPLAINT", USERJOURNAL_COMPLAINT},
	{ "BAN", USERJOURNAL_BAN},
	{ "VOTE", USERJOURNAL_VOTE},
	{ "BEST_VOTE", USERJOURNAL_BEST_VOTE},
	{ "INVENTORY", USERJOURNAL_INVENTORY},
	{ "AUTHID_VOTED", USERJOURNAL_AUTHID_VOTED},
	{ "TOTAL_VOTES_EARNED", USERJOURNAL_TOTAL_VOTES_EARNED},
	{ "ARC_COMPLETED", USERJOURNAL_ARC_COMPLETED},
	{ "DELETE_VOTE", USERJOURNAL_DELETE_VOTE},
	{ "DELETE_BEST_VOTE", USERJOURNAL_DELETE_BEST_VOTE},
	{ "DELETE_AUTHID_VOTED", USERJOURNAL_DELETE_AUTHID_VOTED},
	{ "KEYWORD", USERJOURNAL_KEYWORD},
	{ "ARC_COMPLETED_TIMESTAMP_UPDATE", USERJOURNAL_ARC_COMPLETED_TIMESTAMP_UPDATE},
	{ "ARC_STARTED", USERJOURNAL_ARC_STARTED},
	{ "ARC_STARTED_TIMESTAMP_UPDATE", USERJOURNAL_ARC_STARTED_TIMESTAMP_UPDATE},
	{ "TYPES", USERJOURNAL_TYPES},
	DEFINE_END
};

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ArcJournal
ParseTable parse_ArcJournal[] =
{
	{ "ArcJournal", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ArcJournal), 0, NULL, 0 },
	{ "{",				TOK_START, 0 },
	{ "arcid",			TOK_AUTOINT(ArcJournal, arcid, 0), NULL },
	{ "type",			TOK_AUTOINT(ArcJournal, type, 0), ArcJournalTypeEnum },
	{ "time",			TOK_AUTOINT(ArcJournal, time, 0), NULL },
	{ "rating",			TOK_AUTOINT(ArcJournal, rating, 0), MissionRatingEnum },
	{ "honors",			TOK_AUTOINT(ArcJournal, honors, 0), MissionHonorsEnum },
	{ "ban",			TOK_AUTOINT(ArcJournal, ban, 0), MissionBanEnum },
	{ "votes",			TOK_RAW(ArcJournal, votes), NULL },
	{ "completions",	TOK_AUTOINT(ArcJournal, completions, 0), NULL },
	{ "keyword_votes",	TOK_FIXED_ARRAY | TOK_AUTOINTARRAY(ArcJournal, keyword_votes,  MISSIONSERVER_MAX_KEYWORDS), NULL },
	{ "top_keywords",	TOK_AUTOINT(ArcJournal, top_keywords, 0), NULL },
	{ "starts",			TOK_AUTOINT(ArcJournal, starts, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_ArcJournal()
{
	int iSize = sizeof(ArcJournal);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_ArcJournal, iSize, "ArcJournal", NULL, "MissionServerJournal.c");
	return 0;
};

//autogeneratednocheckin
extern ParseTable parse_MissionServerInventory[];
extern ParseTable parse_MissionServerKeywordVote[];
//Structparser.exe autogenerated ParseTable for struct UserJournal
ParseTable parse_UserJournal[] =
{
	{ "UserJournal", 				TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UserJournal), 0, NULL, 0 },
	{ "{",							TOK_START, 0 },
	{ "auth_id",					TOK_AUTOINT(UserJournal, auth_id, 0), NULL },
	{ "auth_region",				TOK_AUTOINT(UserJournal, auth_region, 0), AuthRegionEnum },
	{ "type",						TOK_AUTOINT(UserJournal, type, 0), UserJournalTypeEnum },
	{ "authid_voted",				TOK_AUTOINT(UserJournal, authid_voted, 0), NULL },
	{ "authid_voted_region",		TOK_AUTOINT(UserJournal, authid_voted_region, 0), AuthRegionEnum },
	{ "authid_voted_timestamp",		TOK_AUTOINT(UserJournal, authid_voted_timestamp, 0), NULL },
	{ "arcid",						TOK_AUTOINT(UserJournal, arcid, 0), NULL },
	{ "arcid_played_timestamp",		TOK_AUTOINT(UserJournal, arcid_played_timestamp, 0), NULL },
	{ "arcid_started_timestamp",	TOK_AUTOINT(UserJournal, arcid_started_timestamp, 0), NULL },
	{ "banned_until",				TOK_AUTOINT(UserJournal, banned_until, 0), NULL },
	{ "autobans",					TOK_AUTOINT(UserJournal, autobans, 0), NULL },
	{ "vote",						TOK_AUTOINT(UserJournal, vote, 0), MissionRatingEnum },
	{ "KeywordVote",				TOK_AUTOINT(UserJournal, keywords, 0), NULL },
	{ "inventory",					TOK_EMBEDDEDSTRUCT(UserJournal, inventory, parse_MissionServerInventory)},
	{ "Keywords",					TOK_EMBEDDEDSTRUCT(UserJournal, ppKeywords, parse_MissionServerKeywordVote)},
	{ "total_votes0",				TOK_AUTOINT(UserJournal, total_votes0, 0), NULL },
	{ "total_votes1",				TOK_AUTOINT(UserJournal, total_votes1, 0), NULL },
	{ "total_votes2",				TOK_AUTOINT(UserJournal, total_votes2, 0), NULL },
	{ "total_votes3",				TOK_AUTOINT(UserJournal, total_votes3, 0), NULL },
	{ "total_votes4",				TOK_AUTOINT(UserJournal, total_votes4, 0), NULL },
	{ "total_votes5",				TOK_AUTOINT(UserJournal, total_votes5, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_UserJournal()
{
	int iSize = sizeof(UserJournal);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_UserJournal, iSize, "UserJournal", NULL, "MissionServerJournal.c");
	return 0;
};

