//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_MissionServer(void);
extern void _MissionServer_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_ArcJournal(void);
extern void autoStruct_fixup_MissionAuth(void);
extern void autoStruct_fixup_MissionComplaint(void);
extern void autoStruct_fixup_MissionHeaderDescription(void);
extern void autoStruct_fixup_MissionSearchGuestBio(void);
extern void autoStruct_fixup_MissionSearchHeader(void);
extern void autoStruct_fixup_MissionSearchParams(void);
extern void autoStruct_fixup_MissionServerArc(void);
extern void autoStruct_fixup_MissionServerCSearch(void);
extern void autoStruct_fixup_MissionServerCfg(void);
extern void autoStruct_fixup_MissionServerQuotedSearch(void);
extern void autoStruct_fixup_MissionServerSearch(void);
extern void autoStruct_fixup_MissionServerShard(void);
extern void autoStruct_fixup_MissionServerSubstringSearch(void);
extern void autoStruct_fixup_MissionServerVars(void);
extern void autoStruct_fixup_UserJournal(void);
void doAutoRuns_ServerLib_0(void);
void doAutoRuns_ServerLib_1(void);
void doAutoRuns_ServerLib_2(void);
void doAutoRuns_ServerLib_3(void);
void doAutoRuns_ServerLib_4(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);


void doAutoRuns_MissionServer_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_ServerLib_0();
	doAutoRuns_UtilitiesLib_0();
	_MissionServer_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_MissionServer_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_ServerLib_1();
	doAutoRuns_UtilitiesLib_1();
	Add_Auto_Cmds_MissionServer();
	autoStruct_fixup_ArcJournal();
	autoStruct_fixup_MissionAuth();
	autoStruct_fixup_MissionComplaint();
	autoStruct_fixup_MissionHeaderDescription();
	autoStruct_fixup_MissionSearchGuestBio();
	autoStruct_fixup_MissionSearchHeader();
	autoStruct_fixup_MissionSearchParams();
	autoStruct_fixup_MissionServerArc();
	autoStruct_fixup_MissionServerCSearch();
	autoStruct_fixup_MissionServerCfg();
	autoStruct_fixup_MissionServerQuotedSearch();
	autoStruct_fixup_MissionServerSearch();
	autoStruct_fixup_MissionServerShard();
	autoStruct_fixup_MissionServerSubstringSearch();
	autoStruct_fixup_MissionServerVars();
	autoStruct_fixup_UserJournal();
}



void doAutoRuns_MissionServer_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_ServerLib_2();
	doAutoRuns_UtilitiesLib_2();
}



void doAutoRuns_MissionServer_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_ServerLib_3();
	doAutoRuns_UtilitiesLib_3();
}



void doAutoRuns_MissionServer_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_ServerLib_4();
	doAutoRuns_UtilitiesLib_4();
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_MissionServer(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_MissionServer_0();
	doAutoRuns_MissionServer_1();
	doAutoRuns_MissionServer_2();
	doAutoRuns_MissionServer_3();
	doAutoRuns_MissionServer_4();
	return 0;
}

};


#if 0
PARSABLE
18
"Add_Auto_Cmds_MissionServer" "autogen_magiccommands" 1 "" "" 
"_MissionServer_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_ArcJournal" "c:\game\code\CoH\MissionServer\.\MissionServerJournal.c" 1 "" "" 
"autoStruct_fixup_MissionAuth" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_MissionComplaint" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_MissionHeaderDescription" "c:\game\code\CoH\MissionServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchGuestBio" "c:\game\code\CoH\MissionServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchHeader" "c:\game\code\CoH\MissionServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchParams" "c:\game\code\CoH\MissionServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionServerArc" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_MissionServerCSearch" "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h" 1 "" "" 
"autoStruct_fixup_MissionServerCfg" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_MissionServerQuotedSearch" "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h" 1 "" "" 
"autoStruct_fixup_MissionServerSearch" "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h" 1 "" "" 
"autoStruct_fixup_MissionServerShard" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_MissionServerSubstringSearch" "c:\game\code\CoH\MissionServer\.\MissionServerSearch.h" 1 "" "" 
"autoStruct_fixup_MissionServerVars" "c:\game\code\CoH\MissionServer\.\MissionServer.h" 1 "" "" 
"autoStruct_fixup_UserJournal" "c:\game\code\CoH\MissionServer\.\MissionServerJournal.c" 1 "" "" 
#endif
