//This file is autogenerated. It contains functions to call all AUTO_COMMANDS
//from the UtilitiesLib project. autogeneratednocheckin

#include "testclientlib_internal.h"

#ifndef CMD_DECLSPEC
#define CMD_DECLSPEC
#endif
//#ifed-out includes to fool incredibuild dependency generation
#if 0
#endif

