//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_AILib(void);
extern void _AILib_AutoRun_SPECIALINTERNAL(void);


void doAutoRuns_AILib_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	_AILib_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_AILib_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	Add_Auto_Cmds_AILib();
}



void doAutoRuns_AILib_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}



void doAutoRuns_AILib_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}



void doAutoRuns_AILib_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_AILib(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_AILib_0();
	doAutoRuns_AILib_1();
	doAutoRuns_AILib_2();
	doAutoRuns_AILib_3();
	doAutoRuns_AILib_4();
	return 0;
}

};


#if 0
PARSABLE
2
"Add_Auto_Cmds_AILib" "autogen_magiccommands" 1 "" "" 
"_AILib_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
#endif
