#ifndef __BONES_H_AST_H_
#define __BONES_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \bones.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\Game\..\Common\seq\bones.h"
#endif



//auto-generated staticdefine for enum BoneId
//autogeneratednocheckin
extern StaticDefineInt BoneIdEnum[];



#endif

