//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_game(void);
extern void _game_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_ArchitectMapComponent(void);
extern void autoStruct_fixup_ArchitectMapComponentPlace(void);
extern void autoStruct_fixup_ArchitectMapHeader(void);
extern void autoStruct_fixup_ArchitectMapSubMap(void);
extern void autoStruct_fixup_LevelRestrict(void);
extern void autoStruct_fixup_MMElement(void);
extern void autoStruct_fixup_MMElementList(void);
extern void autoStruct_fixup_MMRegion(void);
extern void autoStruct_fixup_MMRegionButton(void);
extern void autoStruct_fixup_MMScrollSet_Loader(void);
extern void autoStruct_fixup_MMScrollSet_Mission(void);
extern void autoStruct_fixup_MapLimit(void);
extern void autoStruct_fixup_MissionComment(void);
extern void autoStruct_fixup_MissionCommentList(void);
extern void autoStruct_fixup_MissionHeaderDescription(void);
extern void autoStruct_fixup_MissionSearchGuestBio(void);
extern void autoStruct_fixup_MissionSearchHeader(void);
extern void autoStruct_fixup_MissionSearchParams(void);
void doAutoRuns_nvparse_0(void);
void doAutoRuns_nvparse_1(void);
void doAutoRuns_nvparse_2(void);
void doAutoRuns_nvparse_3(void);
void doAutoRuns_nvparse_4(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);
void doAutoRuns_glew_static_0(void);
void doAutoRuns_glew_static_1(void);
void doAutoRuns_glew_static_2(void);
void doAutoRuns_glew_static_3(void);
void doAutoRuns_glew_static_4(void);


void doAutoRuns_game_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_nvparse_0();
	doAutoRuns_UtilitiesLib_0();
	doAutoRuns_glew_static_0();
	_game_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_game_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_nvparse_1();
	doAutoRuns_UtilitiesLib_1();
	doAutoRuns_glew_static_1();
	Add_Auto_Cmds_game();
	autoStruct_fixup_ArchitectMapComponent();
	autoStruct_fixup_ArchitectMapComponentPlace();
	autoStruct_fixup_ArchitectMapHeader();
	autoStruct_fixup_ArchitectMapSubMap();
	autoStruct_fixup_LevelRestrict();
	autoStruct_fixup_MMElement();
	autoStruct_fixup_MMElementList();
	autoStruct_fixup_MMRegion();
	autoStruct_fixup_MMRegionButton();
	autoStruct_fixup_MMScrollSet_Loader();
	autoStruct_fixup_MMScrollSet_Mission();
	autoStruct_fixup_MapLimit();
	autoStruct_fixup_MissionComment();
	autoStruct_fixup_MissionCommentList();
	autoStruct_fixup_MissionHeaderDescription();
	autoStruct_fixup_MissionSearchGuestBio();
	autoStruct_fixup_MissionSearchHeader();
	autoStruct_fixup_MissionSearchParams();
}



void doAutoRuns_game_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_nvparse_2();
	doAutoRuns_UtilitiesLib_2();
	doAutoRuns_glew_static_2();
}



void doAutoRuns_game_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_nvparse_3();
	doAutoRuns_UtilitiesLib_3();
	doAutoRuns_glew_static_3();
}



void doAutoRuns_game_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_nvparse_4();
	doAutoRuns_UtilitiesLib_4();
	doAutoRuns_glew_static_4();
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_game(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_game_0();
	doAutoRuns_game_1();
	doAutoRuns_game_2();
	doAutoRuns_game_3();
	doAutoRuns_game_4();
	return 0;
}

void do_auto_runs(void)
{
	MagicAutoRunFunc_game();
}

};


#if 0
PARSABLE
20
"Add_Auto_Cmds_game" "autogen_magiccommands" 1 "" "" 
"_game_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_ArchitectMapComponent" "c:\game\code\CoH\Game\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapComponentPlace" "c:\game\code\CoH\Game\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapHeader" "c:\game\code\CoH\Game\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapSubMap" "c:\game\code\CoH\Game\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_LevelRestrict" "c:\game\code\CoH\Game\.\UI\uiMissionMakerScrollSet.h" 1 "" "" 
"autoStruct_fixup_MMElement" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMElementList" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegion" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegionButton" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMScrollSet_Loader" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMScrollSet_Mission" "c:\game\code\CoH\Game\.\UI\uiMissionMakerScrollSet.h" 1 "" "" 
"autoStruct_fixup_MapLimit" "c:\game\code\CoH\Game\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MissionComment" "c:\game\code\CoH\Game\.\UI\uiMissionComment.c" 1 "" "" 
"autoStruct_fixup_MissionCommentList" "c:\game\code\CoH\Game\.\UI\uiMissionComment.c" 1 "" "" 
"autoStruct_fixup_MissionHeaderDescription" "c:\game\code\CoH\Game\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchGuestBio" "c:\game\code\CoH\Game\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchHeader" "c:\game\code\CoH\Game\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchParams" "c:\game\code\CoH\Game\..\Common\MissionSearch.h" 1 "" "" 
#endif
