#ifndef __UIMISSIONMAKERSCROLLSET_H_AST_H_
#define __UIMISSIONMAKERSCROLLSET_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \uiMissionMakerScrollSet.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\Game\.\UI\uiMissionMakerScrollSet.h"
#endif


extern ParseTable parse_LevelRestrict[];

extern ParseTable parse_MMScrollSet_Mission[];


#endif

