#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\Game\.\UI\uiMissionMakerScrollSet.h"
#endif

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct LevelRestrict
ParseTable parse_LevelRestrict[] =
{
	{ "LevelRestrict", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(LevelRestrict), 0, NULL, 0 },
	{ "{",				TOK_START, 0 },
	{ "min",			TOK_AUTOINT(LevelRestrict, min, 0), NULL },
	{ "max",			TOK_AUTOINT(LevelRestrict, max, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_LevelRestrict()
{
	int iSize = sizeof(LevelRestrict);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_LevelRestrict, iSize, "LevelRestrict", NULL, "uiMissionMakerScrollSet.h");
	return 0;
};

//autogeneratednocheckin
extern ParseTable parse_LevelRestrict[];
extern ParseTable parse_MapLimit[];
extern ParseTable parse_MMRegion[];
extern ParseTable parse_MMRegion[];
extern ParseTable parse_MMRegionButton[];
//Structparser.exe autogenerated ParseTable for struct MMScrollSet_Mission
ParseTable parse_MMScrollSet_Mission[] =
{
	{ "MMScrollSet_Mission", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MMScrollSet_Mission), 0, NULL, 0 },
	{ "{",						TOK_START, 0 },
	{ "minLevel",				TOK_AUTOINT(MMScrollSet_Mission, minLevel, 0), NULL },
	{ "maxLevel",				TOK_AUTOINT(MMScrollSet_Mission, maxLevel, 0), NULL },
	{ "minRestrictedLevel",		TOK_AUTOINT(MMScrollSet_Mission, minRestrictedLevel, 0), NULL },
	{ "maxRestrictedLevel",		TOK_AUTOINT(MMScrollSet_Mission, maxRestrictedLevel, 0), NULL },
	{ "Restrict",				TOK_STRUCT(MMScrollSet_Mission, ppRestrict, parse_LevelRestrict) },
	{ "mapCount",				TOK_EMBEDDEDSTRUCT(MMScrollSet_Mission, mapCount, parse_MapLimit)},
	{ "MissionRegion",			TOK_STRUCT(MMScrollSet_Mission, ppMissionRegion, parse_MMRegion) },
	{ "DetailRegion",			TOK_STRUCT(MMScrollSet_Mission, ppDetailRegion, parse_MMRegion) },
	{ "DetailButton",			TOK_STRUCT(MMScrollSet_Mission, ppDetailButton, parse_MMRegionButton) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MMScrollSet_Mission()
{
	int iSize = sizeof(MMScrollSet_Mission);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MMScrollSet_Mission, iSize, "MMScrollSet_Mission", NULL, "uiMissionMakerScrollSet.h");
	return 0;
};

