#ifndef __UIMISSIONCOMMENT_C_AST_H_
#define __UIMISSIONCOMMENT_C_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \uiMissionComment.c
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\Game\.\UI\uiMissionComment.c"
#endif


extern ParseTable parse_MissionComment[];

extern ParseTable parse_MissionCommentList[];


#endif

