#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\Game\.\UI\uiMissionComment.c"
#endif

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MissionComment
ParseTable parse_MissionComment[] =
{
	{ "MissionComment", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionComment), 0, NULL, 0 },
	{ "{",				TOK_START, 0 },
	{ "ArcId",			TOK_AUTOINT(MissionComment, iArcId, 0), NULL },
	{ "Type",			TOK_AUTOINT(MissionComment, eType, 0), NULL },
	{ "Name",			TOK_STRING(MissionComment, pchName, 0), NULL },
	{ "Comment",		TOK_STRING(MissionComment, pchComment, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionComment()
{
	int iSize = sizeof(MissionComment);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionComment, iSize, "MissionComment", NULL, "uiMissionComment.c");
	return 0;
};

//autogeneratednocheckin
extern ParseTable parse_MissionComment[];
//Structparser.exe autogenerated ParseTable for struct MissionCommentList
ParseTable parse_MissionCommentList[] =
{
	{ "MissionCommentList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MissionCommentList), 0, NULL, 0 },
	{ "{",					TOK_START, 0 },
	{ "Comments",			TOK_STRUCT(MissionCommentList, ppComments, parse_MissionComment) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_MissionCommentList()
{
	int iSize = sizeof(MissionCommentList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_MissionCommentList, iSize, "MissionCommentList", NULL, "uiMissionComment.c");
	return 0;
};

