#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\ServerLib\..\Common\persist\persist.h"
#endif



//auto-generated staticdefine for enum PersistType
//autogeneratednocheckin
StaticDefineInt PersistTypeEnum[] =
{
	DEFINE_INT
	{ "Memory", PERSIST_MEMORY},
	{ "Flat", PERSIST_FLAT},
	{ "DiffBig", PERSIST_DIFF_BIG},
	{ "DiffSmall", PERSIST_DIFF_SMALL},
	DEFINE_END
};



//auto-generated staticdefine for enum PersistFlags
//autogeneratednocheckin
StaticDefineInt PersistFlagsEnum[] =
{
	DEFINE_INT
	{ "DEFAULT", PERSIST_DEFAULT},
	{ "ChecksumDb", PERSIST_CRCDB},
	{ "ChecksumJournal", PERSIST_CRCJOURNAL},
	{ "DisableThreads", PERSIST_NOTHREADS},
	{ "BackupDbExponential", PERSIST_EXPONENTIAL},
	{ "BackupJournalLast", PERSIST_KEEPLASTJOURNAL},
	{ "BackupJournalAll", PERSIST_KEEPALLJOURNALS},
	{ "DontSyncMerges", PERSIST_DONTSYNCMERGES},
	DEFINE_END
};

//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct PersistConfig
ParseTable parse_PersistConfig[] =
{
	{ "PersistConfig", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PersistConfig), 0, NULL, 0 },
	{ "configfile",			TOK_CURRENTFILE(PersistConfig, configfile), NULL},
	{ "type",				TOK_AUTOINT(PersistConfig, type, PERSIST_INVALID), PersistTypeEnum },
	{ "flags",				TOK_FLAGS(PersistConfig, flags, PERSIST_DEFAULT), PersistFlagsEnum },
	{ "flushtime",			TOK_AUTOINT(PersistConfig, flush_time, 0), NULL },
	{ "failtime",			TOK_AUTOINT(PersistConfig, fail_time, 0), NULL },
	{ "file",				TOK_STRING(PersistConfig, fname, 0), NULL },
	{ "structname",			TOK_STRING(PersistConfig, structname, 0), NULL },
	{ "max_journal_size",	TOK_AUTOINT(PersistConfig, max_journal_size, 100*1024*1024), NULL },
	{ "roll_journal_tries",	TOK_AUTOINT(PersistConfig, roll_journal_tries, 0), NULL },
	{ "server",				TOK_STRING(PersistConfig, server, 0), NULL },
	{ "user",				TOK_STRING(PersistConfig, user, 0), NULL },
	{ "pass",				TOK_STRING(PersistConfig, pass, 0), NULL },
	{ "db",					TOK_STRING(PersistConfig, db, 0), NULL },
	{ "table",				TOK_STRING(PersistConfig, table, 0), NULL },
	{ "end",				TOK_END, 0 },
	{ "", 0, 0 }
};

int autoStruct_fixup_PersistConfig()
{
	int iSize = sizeof(PersistConfig);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfoExplicitly(parse_PersistConfig, iSize, "PersistConfig", NULL, "persist.h");
	return 0;
};

