#ifndef __PERSIST_INTERNAL_H_AST_H_
#define __PERSIST_INTERNAL_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \persist_internal.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\ServerLib\..\Common\persist\persist_internal.h"
#endif



//auto-generated staticdefine for enum PersistLoadState
//autogeneratednocheckin
extern StaticDefineInt PersistLoadStateEnum[];



//auto-generated staticdefine for enum PersistMergeState
//autogeneratednocheckin
extern StaticDefineInt PersistMergeStateEnum[];



#endif

