#ifndef __PERSIST_H_AST_H_
#define __PERSIST_H_AST_H_
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \persist.h
//autogeneratednocheckin

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\ServerLib\..\Common\persist\persist.h"
#endif



//auto-generated staticdefine for enum PersistType
//autogeneratednocheckin
extern StaticDefineInt PersistTypeEnum[];



//auto-generated staticdefine for enum PersistFlags
//autogeneratednocheckin
extern StaticDefineInt PersistFlagsEnum[];


extern ParseTable parse_PersistConfig[];


#endif

