#include "textparser.h"

//#ifed-out include to fool incredibuild dependencies
#if 0
#include "c:\game\code\CoH\ServerLib\..\Common\persist\persist_internal.h"
#endif



//auto-generated staticdefine for enum PersistLoadState
//autogeneratednocheckin
StaticDefineInt PersistLoadStateEnum[] =
{
	DEFINE_INT
	{ "NOTLOADED", PERSISTINFO_NOTLOADED},
	{ "LOADING", PERSISTINFO_LOADING},
	{ "CLEAN", PERSISTINFO_CLEAN},
	{ "DIRTY", PERSISTINFO_DIRTY},
	{ "QUITTING", PERSISTINFO_QUITTING},
	{ "ERROR", PERSISTINFO_ERROR},
	DEFINE_END
};



//auto-generated staticdefine for enum PersistMergeState
//autogeneratednocheckin
StaticDefineInt PersistMergeStateEnum[] =
{
	DEFINE_INT
	{ "NOTMERGING", PERSISTINFO_NOTMERGING},
	{ "MERGEPENDING", PERSISTINFO_MERGEPENDING},
	{ "MERGING", PERSISTINFO_MERGING},
	DEFINE_END
};

