//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_ServerLib(void);
extern void _ServerLib_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_PersistConfig(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);


void doAutoRuns_ServerLib_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_0();
	_ServerLib_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_ServerLib_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_1();
	Add_Auto_Cmds_ServerLib();
	autoStruct_fixup_PersistConfig();
}



void doAutoRuns_ServerLib_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_2();
}



void doAutoRuns_ServerLib_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_3();
}



void doAutoRuns_ServerLib_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_4();
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_ServerLib(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_ServerLib_0();
	doAutoRuns_ServerLib_1();
	doAutoRuns_ServerLib_2();
	doAutoRuns_ServerLib_3();
	doAutoRuns_ServerLib_4();
	return 0;
}

};


#if 0
PARSABLE
3
"Add_Auto_Cmds_ServerLib" "autogen_magiccommands" 1 "" "" 
"_ServerLib_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_PersistConfig" "c:\game\code\CoH\ServerLib\..\Common\persist\persist.h" 1 "" "" 
#endif
