//This file is autogenerated. It contains function prototypes for all AUTO_COMMANDS
//from the ServerLib project. autogeneratednocheckin
#ifndef CMD_DECLSPEC
#define CMD_DECLSPEC
#endif

//#ifed-out includes to fool incredibuild dependency generation
#if 0
#endif

