//For more info on remote commands, look here: http://code:8081/display/Core/AUTO_COMMAND_REMOTE+and+AUTO_COMMAND_REMOTE_SLOW
//This file is autogenerated. autogeneratednocheckin
#include "RemoteAutoCommandSupport.h"
#include "TextParser.h"
#include "ObjTransactions.h"

//#ifed-out includes to fool incredibuild dependency generation
#if 0
#endif

