//For more info on queued commands, look here: http://code:8081/display/Core/AUTO_COMMAND_QUEUED
//This file is autogenerated. autogeneratednocheckin
#pragma once
#include "commandqueue.h"
#include "estring.h"

//#ifed-out includes to fool incredibuild dependency generation
#if 0
#endif

