//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_TestClient(void);
extern void _TestClient_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_MMElement(void);
extern void autoStruct_fixup_MMElementList(void);
extern void autoStruct_fixup_MMRegion(void);
extern void autoStruct_fixup_MMRegionButton(void);
extern void autoStruct_fixup_MMScrollSet_Loader(void);
extern void autoStruct_fixup_MapLimit(void);
extern void autoStruct_fixup_MissionHeaderDescription(void);
extern void autoStruct_fixup_MissionSearchGuestBio(void);
extern void autoStruct_fixup_MissionSearchHeader(void);
extern void autoStruct_fixup_MissionSearchParams(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);


void doAutoRuns_TestClient_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_0();
	_TestClient_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_TestClient_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_1();
	Add_Auto_Cmds_TestClient();
	autoStruct_fixup_MMElement();
	autoStruct_fixup_MMElementList();
	autoStruct_fixup_MMRegion();
	autoStruct_fixup_MMRegionButton();
	autoStruct_fixup_MMScrollSet_Loader();
	autoStruct_fixup_MapLimit();
	autoStruct_fixup_MissionHeaderDescription();
	autoStruct_fixup_MissionSearchGuestBio();
	autoStruct_fixup_MissionSearchHeader();
	autoStruct_fixup_MissionSearchParams();
}



void doAutoRuns_TestClient_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_2();
}



void doAutoRuns_TestClient_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_3();
}



void doAutoRuns_TestClient_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	doAutoRuns_UtilitiesLib_4();
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_TestClient(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_TestClient_0();
	doAutoRuns_TestClient_1();
	doAutoRuns_TestClient_2();
	doAutoRuns_TestClient_3();
	doAutoRuns_TestClient_4();
	return 0;
}

void do_auto_runs(void)
{
	MagicAutoRunFunc_TestClient();
}

};


#if 0
PARSABLE
12
"Add_Auto_Cmds_TestClient" "autogen_magiccommands" 1 "" "" 
"_TestClient_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_MMElement" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMElementList" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegion" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegionButton" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMScrollSet_Loader" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MapLimit" "c:\game\code\CoH\TestClient\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MissionHeaderDescription" "c:\game\code\CoH\TestClient\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchGuestBio" "c:\game\code\CoH\TestClient\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchHeader" "c:\game\code\CoH\TestClient\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchParams" "c:\game\code\CoH\TestClient\..\Common\MissionSearch.h" 1 "" "" 
#endif
